version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./manuals/.env
    volumes:
      - postgres_manuals_data:/var/lib/postgresql/data
  manuals:
    container_name: app-container
    image: manuals
    build: ./manuals
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 48655:8080
    depends_on:
      - db
    volumes:
      - static_manuals_data:/app/static

volumes:
  postgres_manuals_data:
  static_manuals_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /usr/local/docker/manuals-static-volume
